/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CompanyDataInfo struct for CompanyDataInfo
type CompanyDataInfo struct {
	Id            string                  `json:"id,omitempty"`
	Description   string                  `json:"description,omitempty"`
	WarningType   int64                   `json:"warning_type,omitempty"`
	Industry      CompanyDataInfoIndustry `json:"industry,omitempty"`
	Fund          bool                    `json:"fund,omitempty"`
	Status        string                  `json:"status,omitempty"`
	Currency      string                  `json:"currency,omitempty"`
	Country       string                  `json:"country,omitempty"`
	Employees     int32                   `json:"employees,omitempty"`
	Address       string                  `json:"address,omitempty"`
	YearFounded   int32                   `json:"year_founded,omitempty"`
	Url           string                  `json:"url,omitempty"`
	LogoUrl       string                  `json:"logo_url,omitempty"`
	CoverUrl      string                  `json:"cover_url,omitempty"`
	CoverSmallUrl string                  `json:"cover_small_url,omitempty"`
	Ceo           CompanyDataInfoCeo      `json:"ceo,omitempty"`
	LegalName     string                  `json:"legal_name,omitempty"`
}
