/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// IndustryPerformanceData struct for IndustryPerformanceData
type IndustryPerformanceData struct {
	Top   map[string]IndustryPerformanceDate `json:"top,omitempty"`
	Worst map[string]IndustryPerformanceDate `json:"worst,omitempty"`
}
