/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Ownerships struct for Ownerships
type Ownerships struct {
	Data []Ownership `json:"data,omitempty"`
}
