/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CompanyAnalysisExtendedAnalysisFuture struct for CompanyAnalysisExtendedAnalysisFuture
type CompanyAnalysisExtendedAnalysisFuture struct {
	ReturnOnEquity1y             float32 `json:"return_on_equity_1y,omitempty"`
	ReturnOnEquity3y             float32 `json:"return_on_equity_3y,omitempty"`
	EarningsPerShareGrowth1y     float32 `json:"earnings_per_share_growth_1y,omitempty"`
	EarningsPerShareGrowth3y     float32 `json:"earnings_per_share_growth_3y,omitempty"`
	EarningsPerShare1y           float32 `json:"earnings_per_share_1y,omitempty"`
	EarningsPerShare2y           float32 `json:"earnings_per_share_2y,omitempty"`
	EarningsPerShare3y           float32 `json:"earnings_per_share_3y,omitempty"`
	RevenueGrowth1y              float32 `json:"revenue_growth_1y,omitempty"`
	RevenueGrowth2y              float32 `json:"revenue_growth_2y,omitempty"`
	RevenueGrowth3y              float32 `json:"revenue_growth_3y,omitempty"`
	Revenue1y                    float32 `json:"revenue_1y,omitempty"`
	Revenue2y                    float32 `json:"revenue_2y,omitempty"`
	Revenue3y                    float32 `json:"revenue_3y,omitempty"`
	CashOpsGrowth1y              float32 `json:"cash_ops_growth_1y,omitempty"`
	CashOpsGrowth2y              float32 `json:"cash_ops_growth_2y,omitempty"`
	CashOpsGrowth3y              float32 `json:"cash_ops_growth_3y,omitempty"`
	CashOps1y                    float32 `json:"cash_ops_1y,omitempty"`
	CashOps2y                    float32 `json:"cash_ops_2y,omitempty"`
	CashOps3y                    float32 `json:"cash_ops_3y,omitempty"`
	NetIncomeGrowth1y            float32 `json:"net_income_growth_1y,omitempty"`
	NetIncomeGrowth2y            float32 `json:"net_income_growth_2y,omitempty"`
	NetIncomeGrowth3y            float32 `json:"net_income_growth_3y,omitempty"`
	NetIncome1y                  float32 `json:"net_income_1y,omitempty"`
	NetIncome2y                  float32 `json:"net_income_2y,omitempty"`
	NetIncome3y                  float32 `json:"net_income_3y,omitempty"`
	MinimumEarningsGrowth        float32 `json:"minimum_earnings_growth,omitempty"`
	EarningsPerShareGrowthAnnual float32 `json:"earnings_per_share_growth_annual,omitempty"`
	RevenueGrowthAnnual          float32 `json:"revenue_growth_annual,omitempty"`
	CashOpsGrowthAnnual          float32 `json:"cash_ops_growth_annual,omitempty"`
	NetIncomeGrowthAnnual        float32 `json:"net_income_growth_annual,omitempty"`
	Ebitda1y                     float32 `json:"ebitda_1y,omitempty"`
	EbitdaGrowth1y               float32 `json:"ebitda_growth_1y,omitempty"`
	ForwardPe1y                  float32 `json:"forward_pe_1y,omitempty"`
	ForwardPriceToSales1y        float32 `json:"forward_price_to_sales_1y,omitempty"`
	ForwardEvToEbitda1y          float32 `json:"forward_ev_to_ebitda_1y,omitempty"`
	ForwardEvToSales1y           float32 `json:"forward_ev_to_sales_1y,omitempty"`
	GrossProfitMargin1y          float32 `json:"gross_profit_margin_1y,omitempty"`
	NetIncomeMargin1y            float32 `json:"net_income_margin_1y,omitempty"`
}
