/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CountryFields struct for CountryFields
type CountryFields struct {
	Data *[]CountryField `json:"data,omitempty"`
}

// NewCountryFields instantiates a new CountryFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountryFields() *CountryFields {
	this := CountryFields{}
	return &this
}

// NewCountryFieldsWithDefaults instantiates a new CountryFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryFieldsWithDefaults() *CountryFields {
	this := CountryFields{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CountryFields) GetData() []CountryField {
	if o == nil || o.Data == nil {
		var ret []CountryField
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryFields) GetDataOk() (*[]CountryField, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CountryFields) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []CountryField and assigns it to the Data field.
func (o *CountryFields) SetData(v []CountryField) {
	o.Data = &v
}

func (o CountryFields) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableCountryFields struct {
	value *CountryFields
	isSet bool
}

func (v NullableCountryFields) Get() *CountryFields {
	return v.value
}

func (v *NullableCountryFields) Set(val *CountryFields) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryFields) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryFields(val *CountryFields) *NullableCountryFields {
	return &NullableCountryFields{value: val, isSet: true}
}

func (v NullableCountryFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
