/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Competitors struct for Competitors
type Competitors struct {
	Data []Company `json:"data,omitempty"`
}
