/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CompanyAnalysis struct for CompanyAnalysis
type CompanyAnalysis struct {
	Data CompanyAnalysis `json:"data,omitempty"`
}
