/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MarketPerformance struct for MarketPerformance
type MarketPerformance struct {
	Data MarketPerformanceData `json:"data,omitempty"`
}
