/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CountryLinks struct for CountryLinks
type CountryLinks struct {
	Self string `json:"self,omitempty"`
}
