/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Competitors struct for Competitors
type Competitors struct {
	Data *[]Company `json:"data,omitempty"`
}

// NewCompetitors instantiates a new Competitors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompetitors() *Competitors {
	this := Competitors{}
	return &this
}

// NewCompetitorsWithDefaults instantiates a new Competitors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompetitorsWithDefaults() *Competitors {
	this := Competitors{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Competitors) GetData() []Company {
	if o == nil || o.Data == nil {
		var ret []Company
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Competitors) GetDataOk() (*[]Company, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Competitors) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []Company and assigns it to the Data field.
func (o *Competitors) SetData(v []Company) {
	o.Data = &v
}

func (o Competitors) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableCompetitors struct {
	value *Competitors
	isSet bool
}

func (v NullableCompetitors) Get() *Competitors {
	return v.value
}

func (v *NullableCompetitors) Set(val *Competitors) {
	v.value = val
	v.isSet = true
}

func (v NullableCompetitors) IsSet() bool {
	return v.isSet
}

func (v *NullableCompetitors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompetitors(val *Competitors) *NullableCompetitors {
	return &NullableCompetitors{value: val, isSet: true}
}

func (v NullableCompetitors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompetitors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
