/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CountryLinks struct for CountryLinks
type CountryLinks struct {
	Self *string `json:"self,omitempty"`
}

// NewCountryLinks instantiates a new CountryLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountryLinks() *CountryLinks {
	this := CountryLinks{}
	return &this
}

// NewCountryLinksWithDefaults instantiates a new CountryLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryLinksWithDefaults() *CountryLinks {
	this := CountryLinks{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *CountryLinks) GetSelf() string {
	if o == nil || o.Self == nil {
		var ret string
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryLinks) GetSelfOk() (*string, bool) {
	if o == nil || o.Self == nil {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *CountryLinks) HasSelf() bool {
	if o != nil && o.Self != nil {
		return true
	}

	return false
}

// SetSelf gets a reference to the given string and assigns it to the Self field.
func (o *CountryLinks) SetSelf(v string) {
	o.Self = &v
}

func (o CountryLinks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Self != nil {
		toSerialize["self"] = o.Self
	}
	return json.Marshal(toSerialize)
}

type NullableCountryLinks struct {
	value *CountryLinks
	isSet bool
}

func (v NullableCountryLinks) Get() *CountryLinks {
	return v.value
}

func (v *NullableCountryLinks) Set(val *CountryLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryLinks(val *CountryLinks) *NullableCountryLinks {
	return &NullableCountryLinks{value: val, isSet: true}
}

func (v NullableCountryLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
