/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CompanyAnalysisExtendedAnalysisPast struct for CompanyAnalysisExtendedAnalysisPast
type CompanyAnalysisExtendedAnalysisPast struct {
	Revenue                        float32 `json:"revenue,omitempty"`
	OperatingRevenue               float32 `json:"operating_revenue,omitempty"`
	NetIncome                      float32 `json:"net_income,omitempty"`
	EarningsPerShare               float32 `json:"earnings_per_share,omitempty"`
	EarningsPerShare1y             float32 `json:"earnings_per_share_1y,omitempty"`
	EarningsPerShare3y             float32 `json:"earnings_per_share_3y,omitempty"`
	EarningsPerShare5y             float32 `json:"earnings_per_share_5y,omitempty"`
	EarningsPerShare5yAvg          float32 `json:"earnings_per_share_5y_avg,omitempty"`
	EbtExcluding                   float32 `json:"ebt_excluding,omitempty"`
	EarningsContinuedOps           float32 `json:"earnings_continued_ops,omitempty"`
	TotalAssets                    float32 `json:"total_assets,omitempty"`
	TotalEquity                    float32 `json:"total_equity,omitempty"`
	CurrentLiabilities             float32 `json:"current_liabilities,omitempty"`
	ReturnOnEquity                 float32 `json:"return_on_equity,omitempty"`
	ReturnOnAssets                 float32 `json:"return_on_assets,omitempty"`
	ReturnOnCapitalEmployed        float32 `json:"return_on_capital_employed,omitempty"`
	ReturnOnCapitalEmployedPast    float32 `json:"return_on_capital_employed_past,omitempty"`
	ReturnOnCapitalGrowth          float32 `json:"return_on_capital_growth,omitempty"`
	EarningsPerShareGrowth1y       float32 `json:"earnings_per_share_growth_1y,omitempty"`
	EarningsPerShareGrowth2y       float32 `json:"earnings_per_share_growth_2y,omitempty"`
	EarningsPerShareGrowth3y       float32 `json:"earnings_per_share_growth_3y,omitempty"`
	NetIncome1y                    float32 `json:"net_income_1y,omitempty"`
	NetIncome2y                    float32 `json:"net_income_2y,omitempty"`
	NetIncome3y                    float32 `json:"net_income_3y,omitempty"`
	NetIncome4y                    float32 `json:"net_income_4y,omitempty"`
	NetIncome5y                    float32 `json:"net_income_5y,omitempty"`
	NetIncome5yAvg                 float32 `json:"net_income_5y_avg,omitempty"`
	NetIncomeGrowth1y              float32 `json:"net_income_growth_1y,omitempty"`
	NetIncomeGrowth3y              float32 `json:"net_income_growth_3y,omitempty"`
	NetIncomeGrowth5y              float32 `json:"net_income_growth_5y,omitempty"`
	RevenueGrowth1y                float32 `json:"revenue_growth_1y,omitempty"`
	RevenueGrowth3y                float32 `json:"revenue_growth_3y,omitempty"`
	RevenueGrowth5y                float32 `json:"revenue_growth_5y,omitempty"`
	DaysSinceLastUpdate            int32   `json:"days_since_last_update,omitempty"`
	LastEarningsUpdate             float32 `json:"last_earnings_update,omitempty"`
	LastEarningsUpdateAnnual       float32 `json:"last_earnings_update_annual,omitempty"`
	Ebit                           float32 `json:"ebit,omitempty"`
	Ebit3yAvg                      float32 `json:"ebit_3y_avg,omitempty"`
	Ebit5yAvg                      float32 `json:"ebit_5y_avg,omitempty"`
	EbitSingleGrowth1y             float32 `json:"ebit_single_growth_1y,omitempty"`
	EbitSingleGrowth3y             float32 `json:"ebit_single_growth_3y,omitempty"`
	EbitSingleGrowth5y             float32 `json:"ebit_single_growth_5y,omitempty"`
	EbitMargin1y                   float32 `json:"ebit_margin_1y,omitempty"`
	EbitMargin                     float32 `json:"ebit_margin,omitempty"`
	Ebitda                         float32 `json:"ebitda,omitempty"`
	EbitdaMargin                   float32 `json:"ebitda_margin,omitempty"`
	GrossProfitMargin              float32 `json:"gross_profit_margin,omitempty"`
	NetIncomeSingleGrowth3y        float32 `json:"net_income_single_growth_3y,omitempty"`
	NetIncomeSingleGrowth5y        float32 `json:"net_income_single_growth_5y,omitempty"`
	EarningsPerShareSingleGrowth3y float32 `json:"earnings_per_share_single_growth_3y,omitempty"`
	EarningsPerShareSingleGrowth5y float32 `json:"earnings_per_share_single_growth_5y,omitempty"`
	GrossProfitMargin1y            float32 `json:"gross_profit_margin_1y,omitempty"`
	NetIncomeMargin                float32 `json:"net_income_margin,omitempty"`
	NetIncomeMargin1y              float32 `json:"net_income_margin_1y,omitempty"`
	ChangeInUnearnedRevenue        float32 `json:"change_in_unearned_revenue,omitempty"`
	UnearnedRevenuePercentOfSales  float32 `json:"unearned_revenue_percent_of_sales,omitempty"`
	EbtIncluding                   float32 `json:"ebt_including,omitempty"`
	UnusualItems                   float32 `json:"unusual_items,omitempty"`
	UnusualItemRatio               float32 `json:"unusual_item_ratio,omitempty"`
	OperatingRevenuePercent        float32 `json:"operating_revenue_percent,omitempty"`
	YearsProfitable                float32 `json:"years_profitable,omitempty"`
	TradingSinceYears              float32 `json:"trading_since_years,omitempty"`
	NonOperatingRevenue            float32 `json:"non_operating_revenue,omitempty"`
	NonOperatingRevenueRatio       float32 `json:"non_operating_revenue_ratio,omitempty"`
	NonOperatingRevenueRatio1y     float32 `json:"non_operating_revenue_ratio_1y,omitempty"`
	NonOperatingRevenueRatioDelta  float32 `json:"non_operating_revenue_ratio_delta,omitempty"`
	IncomeTaxToEbitRatio           float32 `json:"income_tax_to_ebit_ratio,omitempty"`
	LatestFiscalYear               int32   `json:"latest_fiscal_year,omitempty"`
	LatestFiscalQuarter            int32   `json:"latest_fiscal_quarter,omitempty"`
}
