/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// IndustryCountryCountries struct for IndustryCountryCountries
type IndustryCountryCountries struct {
	Data []Country `json:"data,omitempty"`
}
