/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CompanyAnalysisExtendedAnalysisHealth struct for CompanyAnalysisExtendedAnalysisHealth
type CompanyAnalysisExtendedAnalysisHealth struct {
	NetIncome                         *float64 `json:"net_income,omitempty"`
	NetInterestExpense                *float64 `json:"net_interest_expense,omitempty"`
	CashOperating                     *float64 `json:"cash_operating,omitempty"`
	TotalAssets                       *float64 `json:"total_assets,omitempty"`
	Ppe                               *float64 `json:"ppe,omitempty"`
	Inventory                         *float64 `json:"inventory,omitempty"`
	CashStInvestments                 *float64 `json:"cash_st_investments,omitempty"`
	Receivables                       *float64 `json:"receivables,omitempty"`
	CurrentAssets                     *float64 `json:"current_assets,omitempty"`
	TotalEquity                       *float64 `json:"total_equity,omitempty"`
	TotalDebt                         *float64 `json:"total_debt,omitempty"`
	LongTermDebt                      *float64 `json:"long_term_debt,omitempty"`
	LongTermLiab                      *float64 `json:"long_term_liab,omitempty"`
	AccountsPayable                   *float64 `json:"accounts_payable,omitempty"`
	TotalCurrentLiab                  *float64 `json:"total_current_liab,omitempty"`
	TotalLiabEquity                   *float64 `json:"total_liab_equity,omitempty"`
	TotalDebtEquity                   *float64 `json:"total_debt_equity,omitempty"`
	TotalInventory                    *float64 `json:"total_inventory,omitempty"`
	DebtToEquityRatio                 *float64 `json:"debt_to_equity_ratio,omitempty"`
	DebtToEquityRatioPast             *float64 `json:"debt_to_equity_ratio_past,omitempty"`
	AssetsEquityRatio                 *float64 `json:"assets_equity_ratio,omitempty"`
	FixedToTotalAssets                *float64 `json:"fixed_to_total_assets,omitempty"`
	CurrentAssetsToTotalDebt          *float64 `json:"current_assets_to_total_debt,omitempty"`
	OperatingCashFlowToTotalDebt      *float64 `json:"operating_cash_flow_to_total_debt,omitempty"`
	NetInterestCover                  *float64 `json:"net_interest_cover,omitempty"`
	CurrentSolvencyRatio              *float64 `json:"current_solvency_ratio,omitempty"`
	CurrentAssetsToLongTermLiab       *float64 `json:"current_assets_to_long_term_liab,omitempty"`
	OperatingExpenses                 *float64 `json:"operating_expenses,omitempty"`
	OperatingExpensesGrowthAnnual     *float64 `json:"operating_expenses_growth_annual,omitempty"`
	OperatingExpensesStableYears      *float64 `json:"operating_expenses_stable_years,omitempty"`
	OperatingExpensesGrowthYears      *float64 `json:"operating_expenses_growth_years,omitempty"`
	Median2yrNetIncome                *float64 `json:"median_2yr_net_income,omitempty"`
	Capex                             *float64 `json:"capex,omitempty"`
	CapexGrowth1y                     *float64 `json:"capex_growth_1y,omitempty"`
	CapexGrowthAnnual                 *float64 `json:"capex_growth_annual,omitempty"`
	NetDebt                           *float64 `json:"net_debt,omitempty"`
	ManagementRateReturn              *float64 `json:"management_rate_return,omitempty"`
	BookValuePerShare                 *float64 `json:"book_value_per_share,omitempty"`
	LeveredFreeCashFlow               *float64 `json:"levered_free_cash_flow,omitempty"`
	LeveredFreeCashFlow1y             *float64 `json:"levered_free_cash_flow_1y,omitempty"`
	LeveredFreeCashFlow2y             *float64 `json:"levered_free_cash_flow_2y,omitempty"`
	LeveredFreeCashGrowthAnnual       *float64 `json:"levered_free_cash_growth_annual,omitempty"`
	LeveredFreeCashFlowGrowthAnnual   *float64 `json:"levered_free_cash_flow_growth_annual,omitempty"`
	LeveredFreeCashFlowGrowthYears    *float64 `json:"levered_free_cash_flow_growth_years,omitempty"`
	LeveredFreeCashFlowStableYears    *float64 `json:"levered_free_cash_flow_stable_years,omitempty"`
	CashFromInvesting                 *float64 `json:"cash_from_investing,omitempty"`
	NetDebtToEbitda                   *float64 `json:"net_debt_to_ebitda,omitempty"`
	CapitalisationPercent             *float64 `json:"capitalisation_percent,omitempty"`
	CapitalisationPercent1y           *float64 `json:"capitalisation_percent_1y,omitempty"`
	CashOperatingGrowth1y             *float64 `json:"cash_operating_growth_1y,omitempty"`
	CashFromInvesting1y               *float64 `json:"cash_from_investing_1y,omitempty"`
	InventoryGrowth1y                 *float64 `json:"inventory_growth_1y,omitempty"`
	NetOperatingAssets                *float64 `json:"net_operating_assets,omitempty"`
	NetOperatingAssets1y              *float64 `json:"net_operating_assets_1y,omitempty"`
	AggregateAccruals                 *float64 `json:"aggregate_accruals,omitempty"`
	AccountsReceivableGrowth1y        *float64 `json:"accounts_receivable_growth_1y,omitempty"`
	AccountsReceivablePercent         *float64 `json:"accounts_receivable_percent,omitempty"`
	LongTermAssets                    *float64 `json:"long_term_assets,omitempty"`
	LastBalanceSheetUpdate            *float64 `json:"last_balance_sheet_update,omitempty"`
	CurrentPortionLeaseLiabilities    *float64 `json:"current_portion_lease_liabilities,omitempty"`
	LongTermPortionLeaseLiabilities   *float64 `json:"long_term_portion_lease_liabilities,omitempty"`
	TotalLeaseLiabilities             *float64 `json:"total_lease_liabilities,omitempty"`
	RestrictedCash                    *float64 `json:"restricted_cash,omitempty"`
	RestrictedCashRatio               *float64 `json:"restricted_cash_ratio,omitempty"`
	LeveredFreeCashFlowBreakEvenYears *float64 `json:"levered_free_cash_flow_break_even_years,omitempty"`
}

// NewCompanyAnalysisExtendedAnalysisHealth instantiates a new CompanyAnalysisExtendedAnalysisHealth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyAnalysisExtendedAnalysisHealth() *CompanyAnalysisExtendedAnalysisHealth {
	this := CompanyAnalysisExtendedAnalysisHealth{}
	return &this
}

// NewCompanyAnalysisExtendedAnalysisHealthWithDefaults instantiates a new CompanyAnalysisExtendedAnalysisHealth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyAnalysisExtendedAnalysisHealthWithDefaults() *CompanyAnalysisExtendedAnalysisHealth {
	this := CompanyAnalysisExtendedAnalysisHealth{}
	return &this
}

// GetNetIncome returns the NetIncome field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetNetIncome() float64 {
	if o == nil || o.NetIncome == nil {
		var ret float64
		return ret
	}
	return *o.NetIncome
}

// GetNetIncomeOk returns a tuple with the NetIncome field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetNetIncomeOk() (*float64, bool) {
	if o == nil || o.NetIncome == nil {
		return nil, false
	}
	return o.NetIncome, true
}

// HasNetIncome returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasNetIncome() bool {
	if o != nil && o.NetIncome != nil {
		return true
	}

	return false
}

// SetNetIncome gets a reference to the given float64 and assigns it to the NetIncome field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetNetIncome(v float64) {
	o.NetIncome = &v
}

// GetNetInterestExpense returns the NetInterestExpense field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetNetInterestExpense() float64 {
	if o == nil || o.NetInterestExpense == nil {
		var ret float64
		return ret
	}
	return *o.NetInterestExpense
}

// GetNetInterestExpenseOk returns a tuple with the NetInterestExpense field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetNetInterestExpenseOk() (*float64, bool) {
	if o == nil || o.NetInterestExpense == nil {
		return nil, false
	}
	return o.NetInterestExpense, true
}

// HasNetInterestExpense returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasNetInterestExpense() bool {
	if o != nil && o.NetInterestExpense != nil {
		return true
	}

	return false
}

// SetNetInterestExpense gets a reference to the given float64 and assigns it to the NetInterestExpense field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetNetInterestExpense(v float64) {
	o.NetInterestExpense = &v
}

// GetCashOperating returns the CashOperating field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCashOperating() float64 {
	if o == nil || o.CashOperating == nil {
		var ret float64
		return ret
	}
	return *o.CashOperating
}

// GetCashOperatingOk returns a tuple with the CashOperating field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCashOperatingOk() (*float64, bool) {
	if o == nil || o.CashOperating == nil {
		return nil, false
	}
	return o.CashOperating, true
}

// HasCashOperating returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasCashOperating() bool {
	if o != nil && o.CashOperating != nil {
		return true
	}

	return false
}

// SetCashOperating gets a reference to the given float64 and assigns it to the CashOperating field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetCashOperating(v float64) {
	o.CashOperating = &v
}

// GetTotalAssets returns the TotalAssets field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalAssets() float64 {
	if o == nil || o.TotalAssets == nil {
		var ret float64
		return ret
	}
	return *o.TotalAssets
}

// GetTotalAssetsOk returns a tuple with the TotalAssets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalAssetsOk() (*float64, bool) {
	if o == nil || o.TotalAssets == nil {
		return nil, false
	}
	return o.TotalAssets, true
}

// HasTotalAssets returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasTotalAssets() bool {
	if o != nil && o.TotalAssets != nil {
		return true
	}

	return false
}

// SetTotalAssets gets a reference to the given float64 and assigns it to the TotalAssets field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetTotalAssets(v float64) {
	o.TotalAssets = &v
}

// GetPpe returns the Ppe field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetPpe() float64 {
	if o == nil || o.Ppe == nil {
		var ret float64
		return ret
	}
	return *o.Ppe
}

// GetPpeOk returns a tuple with the Ppe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetPpeOk() (*float64, bool) {
	if o == nil || o.Ppe == nil {
		return nil, false
	}
	return o.Ppe, true
}

// HasPpe returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasPpe() bool {
	if o != nil && o.Ppe != nil {
		return true
	}

	return false
}

// SetPpe gets a reference to the given float64 and assigns it to the Ppe field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetPpe(v float64) {
	o.Ppe = &v
}

// GetInventory returns the Inventory field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetInventory() float64 {
	if o == nil || o.Inventory == nil {
		var ret float64
		return ret
	}
	return *o.Inventory
}

// GetInventoryOk returns a tuple with the Inventory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetInventoryOk() (*float64, bool) {
	if o == nil || o.Inventory == nil {
		return nil, false
	}
	return o.Inventory, true
}

// HasInventory returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasInventory() bool {
	if o != nil && o.Inventory != nil {
		return true
	}

	return false
}

// SetInventory gets a reference to the given float64 and assigns it to the Inventory field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetInventory(v float64) {
	o.Inventory = &v
}

// GetCashStInvestments returns the CashStInvestments field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCashStInvestments() float64 {
	if o == nil || o.CashStInvestments == nil {
		var ret float64
		return ret
	}
	return *o.CashStInvestments
}

// GetCashStInvestmentsOk returns a tuple with the CashStInvestments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCashStInvestmentsOk() (*float64, bool) {
	if o == nil || o.CashStInvestments == nil {
		return nil, false
	}
	return o.CashStInvestments, true
}

// HasCashStInvestments returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasCashStInvestments() bool {
	if o != nil && o.CashStInvestments != nil {
		return true
	}

	return false
}

// SetCashStInvestments gets a reference to the given float64 and assigns it to the CashStInvestments field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetCashStInvestments(v float64) {
	o.CashStInvestments = &v
}

// GetReceivables returns the Receivables field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetReceivables() float64 {
	if o == nil || o.Receivables == nil {
		var ret float64
		return ret
	}
	return *o.Receivables
}

// GetReceivablesOk returns a tuple with the Receivables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetReceivablesOk() (*float64, bool) {
	if o == nil || o.Receivables == nil {
		return nil, false
	}
	return o.Receivables, true
}

// HasReceivables returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasReceivables() bool {
	if o != nil && o.Receivables != nil {
		return true
	}

	return false
}

// SetReceivables gets a reference to the given float64 and assigns it to the Receivables field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetReceivables(v float64) {
	o.Receivables = &v
}

// GetCurrentAssets returns the CurrentAssets field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCurrentAssets() float64 {
	if o == nil || o.CurrentAssets == nil {
		var ret float64
		return ret
	}
	return *o.CurrentAssets
}

// GetCurrentAssetsOk returns a tuple with the CurrentAssets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCurrentAssetsOk() (*float64, bool) {
	if o == nil || o.CurrentAssets == nil {
		return nil, false
	}
	return o.CurrentAssets, true
}

// HasCurrentAssets returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasCurrentAssets() bool {
	if o != nil && o.CurrentAssets != nil {
		return true
	}

	return false
}

// SetCurrentAssets gets a reference to the given float64 and assigns it to the CurrentAssets field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetCurrentAssets(v float64) {
	o.CurrentAssets = &v
}

// GetTotalEquity returns the TotalEquity field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalEquity() float64 {
	if o == nil || o.TotalEquity == nil {
		var ret float64
		return ret
	}
	return *o.TotalEquity
}

// GetTotalEquityOk returns a tuple with the TotalEquity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalEquityOk() (*float64, bool) {
	if o == nil || o.TotalEquity == nil {
		return nil, false
	}
	return o.TotalEquity, true
}

// HasTotalEquity returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasTotalEquity() bool {
	if o != nil && o.TotalEquity != nil {
		return true
	}

	return false
}

// SetTotalEquity gets a reference to the given float64 and assigns it to the TotalEquity field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetTotalEquity(v float64) {
	o.TotalEquity = &v
}

// GetTotalDebt returns the TotalDebt field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalDebt() float64 {
	if o == nil || o.TotalDebt == nil {
		var ret float64
		return ret
	}
	return *o.TotalDebt
}

// GetTotalDebtOk returns a tuple with the TotalDebt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalDebtOk() (*float64, bool) {
	if o == nil || o.TotalDebt == nil {
		return nil, false
	}
	return o.TotalDebt, true
}

// HasTotalDebt returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasTotalDebt() bool {
	if o != nil && o.TotalDebt != nil {
		return true
	}

	return false
}

// SetTotalDebt gets a reference to the given float64 and assigns it to the TotalDebt field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetTotalDebt(v float64) {
	o.TotalDebt = &v
}

// GetLongTermDebt returns the LongTermDebt field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLongTermDebt() float64 {
	if o == nil || o.LongTermDebt == nil {
		var ret float64
		return ret
	}
	return *o.LongTermDebt
}

// GetLongTermDebtOk returns a tuple with the LongTermDebt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLongTermDebtOk() (*float64, bool) {
	if o == nil || o.LongTermDebt == nil {
		return nil, false
	}
	return o.LongTermDebt, true
}

// HasLongTermDebt returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasLongTermDebt() bool {
	if o != nil && o.LongTermDebt != nil {
		return true
	}

	return false
}

// SetLongTermDebt gets a reference to the given float64 and assigns it to the LongTermDebt field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetLongTermDebt(v float64) {
	o.LongTermDebt = &v
}

// GetLongTermLiab returns the LongTermLiab field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLongTermLiab() float64 {
	if o == nil || o.LongTermLiab == nil {
		var ret float64
		return ret
	}
	return *o.LongTermLiab
}

// GetLongTermLiabOk returns a tuple with the LongTermLiab field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLongTermLiabOk() (*float64, bool) {
	if o == nil || o.LongTermLiab == nil {
		return nil, false
	}
	return o.LongTermLiab, true
}

// HasLongTermLiab returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasLongTermLiab() bool {
	if o != nil && o.LongTermLiab != nil {
		return true
	}

	return false
}

// SetLongTermLiab gets a reference to the given float64 and assigns it to the LongTermLiab field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetLongTermLiab(v float64) {
	o.LongTermLiab = &v
}

// GetAccountsPayable returns the AccountsPayable field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetAccountsPayable() float64 {
	if o == nil || o.AccountsPayable == nil {
		var ret float64
		return ret
	}
	return *o.AccountsPayable
}

// GetAccountsPayableOk returns a tuple with the AccountsPayable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetAccountsPayableOk() (*float64, bool) {
	if o == nil || o.AccountsPayable == nil {
		return nil, false
	}
	return o.AccountsPayable, true
}

// HasAccountsPayable returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasAccountsPayable() bool {
	if o != nil && o.AccountsPayable != nil {
		return true
	}

	return false
}

// SetAccountsPayable gets a reference to the given float64 and assigns it to the AccountsPayable field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetAccountsPayable(v float64) {
	o.AccountsPayable = &v
}

// GetTotalCurrentLiab returns the TotalCurrentLiab field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalCurrentLiab() float64 {
	if o == nil || o.TotalCurrentLiab == nil {
		var ret float64
		return ret
	}
	return *o.TotalCurrentLiab
}

// GetTotalCurrentLiabOk returns a tuple with the TotalCurrentLiab field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalCurrentLiabOk() (*float64, bool) {
	if o == nil || o.TotalCurrentLiab == nil {
		return nil, false
	}
	return o.TotalCurrentLiab, true
}

// HasTotalCurrentLiab returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasTotalCurrentLiab() bool {
	if o != nil && o.TotalCurrentLiab != nil {
		return true
	}

	return false
}

// SetTotalCurrentLiab gets a reference to the given float64 and assigns it to the TotalCurrentLiab field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetTotalCurrentLiab(v float64) {
	o.TotalCurrentLiab = &v
}

// GetTotalLiabEquity returns the TotalLiabEquity field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalLiabEquity() float64 {
	if o == nil || o.TotalLiabEquity == nil {
		var ret float64
		return ret
	}
	return *o.TotalLiabEquity
}

// GetTotalLiabEquityOk returns a tuple with the TotalLiabEquity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalLiabEquityOk() (*float64, bool) {
	if o == nil || o.TotalLiabEquity == nil {
		return nil, false
	}
	return o.TotalLiabEquity, true
}

// HasTotalLiabEquity returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasTotalLiabEquity() bool {
	if o != nil && o.TotalLiabEquity != nil {
		return true
	}

	return false
}

// SetTotalLiabEquity gets a reference to the given float64 and assigns it to the TotalLiabEquity field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetTotalLiabEquity(v float64) {
	o.TotalLiabEquity = &v
}

// GetTotalDebtEquity returns the TotalDebtEquity field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalDebtEquity() float64 {
	if o == nil || o.TotalDebtEquity == nil {
		var ret float64
		return ret
	}
	return *o.TotalDebtEquity
}

// GetTotalDebtEquityOk returns a tuple with the TotalDebtEquity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalDebtEquityOk() (*float64, bool) {
	if o == nil || o.TotalDebtEquity == nil {
		return nil, false
	}
	return o.TotalDebtEquity, true
}

// HasTotalDebtEquity returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasTotalDebtEquity() bool {
	if o != nil && o.TotalDebtEquity != nil {
		return true
	}

	return false
}

// SetTotalDebtEquity gets a reference to the given float64 and assigns it to the TotalDebtEquity field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetTotalDebtEquity(v float64) {
	o.TotalDebtEquity = &v
}

// GetTotalInventory returns the TotalInventory field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalInventory() float64 {
	if o == nil || o.TotalInventory == nil {
		var ret float64
		return ret
	}
	return *o.TotalInventory
}

// GetTotalInventoryOk returns a tuple with the TotalInventory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalInventoryOk() (*float64, bool) {
	if o == nil || o.TotalInventory == nil {
		return nil, false
	}
	return o.TotalInventory, true
}

// HasTotalInventory returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasTotalInventory() bool {
	if o != nil && o.TotalInventory != nil {
		return true
	}

	return false
}

// SetTotalInventory gets a reference to the given float64 and assigns it to the TotalInventory field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetTotalInventory(v float64) {
	o.TotalInventory = &v
}

// GetDebtToEquityRatio returns the DebtToEquityRatio field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetDebtToEquityRatio() float64 {
	if o == nil || o.DebtToEquityRatio == nil {
		var ret float64
		return ret
	}
	return *o.DebtToEquityRatio
}

// GetDebtToEquityRatioOk returns a tuple with the DebtToEquityRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetDebtToEquityRatioOk() (*float64, bool) {
	if o == nil || o.DebtToEquityRatio == nil {
		return nil, false
	}
	return o.DebtToEquityRatio, true
}

// HasDebtToEquityRatio returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasDebtToEquityRatio() bool {
	if o != nil && o.DebtToEquityRatio != nil {
		return true
	}

	return false
}

// SetDebtToEquityRatio gets a reference to the given float64 and assigns it to the DebtToEquityRatio field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetDebtToEquityRatio(v float64) {
	o.DebtToEquityRatio = &v
}

// GetDebtToEquityRatioPast returns the DebtToEquityRatioPast field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetDebtToEquityRatioPast() float64 {
	if o == nil || o.DebtToEquityRatioPast == nil {
		var ret float64
		return ret
	}
	return *o.DebtToEquityRatioPast
}

// GetDebtToEquityRatioPastOk returns a tuple with the DebtToEquityRatioPast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetDebtToEquityRatioPastOk() (*float64, bool) {
	if o == nil || o.DebtToEquityRatioPast == nil {
		return nil, false
	}
	return o.DebtToEquityRatioPast, true
}

// HasDebtToEquityRatioPast returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasDebtToEquityRatioPast() bool {
	if o != nil && o.DebtToEquityRatioPast != nil {
		return true
	}

	return false
}

// SetDebtToEquityRatioPast gets a reference to the given float64 and assigns it to the DebtToEquityRatioPast field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetDebtToEquityRatioPast(v float64) {
	o.DebtToEquityRatioPast = &v
}

// GetAssetsEquityRatio returns the AssetsEquityRatio field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetAssetsEquityRatio() float64 {
	if o == nil || o.AssetsEquityRatio == nil {
		var ret float64
		return ret
	}
	return *o.AssetsEquityRatio
}

// GetAssetsEquityRatioOk returns a tuple with the AssetsEquityRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetAssetsEquityRatioOk() (*float64, bool) {
	if o == nil || o.AssetsEquityRatio == nil {
		return nil, false
	}
	return o.AssetsEquityRatio, true
}

// HasAssetsEquityRatio returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasAssetsEquityRatio() bool {
	if o != nil && o.AssetsEquityRatio != nil {
		return true
	}

	return false
}

// SetAssetsEquityRatio gets a reference to the given float64 and assigns it to the AssetsEquityRatio field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetAssetsEquityRatio(v float64) {
	o.AssetsEquityRatio = &v
}

// GetFixedToTotalAssets returns the FixedToTotalAssets field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetFixedToTotalAssets() float64 {
	if o == nil || o.FixedToTotalAssets == nil {
		var ret float64
		return ret
	}
	return *o.FixedToTotalAssets
}

// GetFixedToTotalAssetsOk returns a tuple with the FixedToTotalAssets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetFixedToTotalAssetsOk() (*float64, bool) {
	if o == nil || o.FixedToTotalAssets == nil {
		return nil, false
	}
	return o.FixedToTotalAssets, true
}

// HasFixedToTotalAssets returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasFixedToTotalAssets() bool {
	if o != nil && o.FixedToTotalAssets != nil {
		return true
	}

	return false
}

// SetFixedToTotalAssets gets a reference to the given float64 and assigns it to the FixedToTotalAssets field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetFixedToTotalAssets(v float64) {
	o.FixedToTotalAssets = &v
}

// GetCurrentAssetsToTotalDebt returns the CurrentAssetsToTotalDebt field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCurrentAssetsToTotalDebt() float64 {
	if o == nil || o.CurrentAssetsToTotalDebt == nil {
		var ret float64
		return ret
	}
	return *o.CurrentAssetsToTotalDebt
}

// GetCurrentAssetsToTotalDebtOk returns a tuple with the CurrentAssetsToTotalDebt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCurrentAssetsToTotalDebtOk() (*float64, bool) {
	if o == nil || o.CurrentAssetsToTotalDebt == nil {
		return nil, false
	}
	return o.CurrentAssetsToTotalDebt, true
}

// HasCurrentAssetsToTotalDebt returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasCurrentAssetsToTotalDebt() bool {
	if o != nil && o.CurrentAssetsToTotalDebt != nil {
		return true
	}

	return false
}

// SetCurrentAssetsToTotalDebt gets a reference to the given float64 and assigns it to the CurrentAssetsToTotalDebt field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetCurrentAssetsToTotalDebt(v float64) {
	o.CurrentAssetsToTotalDebt = &v
}

// GetOperatingCashFlowToTotalDebt returns the OperatingCashFlowToTotalDebt field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetOperatingCashFlowToTotalDebt() float64 {
	if o == nil || o.OperatingCashFlowToTotalDebt == nil {
		var ret float64
		return ret
	}
	return *o.OperatingCashFlowToTotalDebt
}

// GetOperatingCashFlowToTotalDebtOk returns a tuple with the OperatingCashFlowToTotalDebt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetOperatingCashFlowToTotalDebtOk() (*float64, bool) {
	if o == nil || o.OperatingCashFlowToTotalDebt == nil {
		return nil, false
	}
	return o.OperatingCashFlowToTotalDebt, true
}

// HasOperatingCashFlowToTotalDebt returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasOperatingCashFlowToTotalDebt() bool {
	if o != nil && o.OperatingCashFlowToTotalDebt != nil {
		return true
	}

	return false
}

// SetOperatingCashFlowToTotalDebt gets a reference to the given float64 and assigns it to the OperatingCashFlowToTotalDebt field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetOperatingCashFlowToTotalDebt(v float64) {
	o.OperatingCashFlowToTotalDebt = &v
}

// GetNetInterestCover returns the NetInterestCover field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetNetInterestCover() float64 {
	if o == nil || o.NetInterestCover == nil {
		var ret float64
		return ret
	}
	return *o.NetInterestCover
}

// GetNetInterestCoverOk returns a tuple with the NetInterestCover field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetNetInterestCoverOk() (*float64, bool) {
	if o == nil || o.NetInterestCover == nil {
		return nil, false
	}
	return o.NetInterestCover, true
}

// HasNetInterestCover returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasNetInterestCover() bool {
	if o != nil && o.NetInterestCover != nil {
		return true
	}

	return false
}

// SetNetInterestCover gets a reference to the given float64 and assigns it to the NetInterestCover field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetNetInterestCover(v float64) {
	o.NetInterestCover = &v
}

// GetCurrentSolvencyRatio returns the CurrentSolvencyRatio field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCurrentSolvencyRatio() float64 {
	if o == nil || o.CurrentSolvencyRatio == nil {
		var ret float64
		return ret
	}
	return *o.CurrentSolvencyRatio
}

// GetCurrentSolvencyRatioOk returns a tuple with the CurrentSolvencyRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCurrentSolvencyRatioOk() (*float64, bool) {
	if o == nil || o.CurrentSolvencyRatio == nil {
		return nil, false
	}
	return o.CurrentSolvencyRatio, true
}

// HasCurrentSolvencyRatio returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasCurrentSolvencyRatio() bool {
	if o != nil && o.CurrentSolvencyRatio != nil {
		return true
	}

	return false
}

// SetCurrentSolvencyRatio gets a reference to the given float64 and assigns it to the CurrentSolvencyRatio field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetCurrentSolvencyRatio(v float64) {
	o.CurrentSolvencyRatio = &v
}

// GetCurrentAssetsToLongTermLiab returns the CurrentAssetsToLongTermLiab field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCurrentAssetsToLongTermLiab() float64 {
	if o == nil || o.CurrentAssetsToLongTermLiab == nil {
		var ret float64
		return ret
	}
	return *o.CurrentAssetsToLongTermLiab
}

// GetCurrentAssetsToLongTermLiabOk returns a tuple with the CurrentAssetsToLongTermLiab field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCurrentAssetsToLongTermLiabOk() (*float64, bool) {
	if o == nil || o.CurrentAssetsToLongTermLiab == nil {
		return nil, false
	}
	return o.CurrentAssetsToLongTermLiab, true
}

// HasCurrentAssetsToLongTermLiab returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasCurrentAssetsToLongTermLiab() bool {
	if o != nil && o.CurrentAssetsToLongTermLiab != nil {
		return true
	}

	return false
}

// SetCurrentAssetsToLongTermLiab gets a reference to the given float64 and assigns it to the CurrentAssetsToLongTermLiab field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetCurrentAssetsToLongTermLiab(v float64) {
	o.CurrentAssetsToLongTermLiab = &v
}

// GetOperatingExpenses returns the OperatingExpenses field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetOperatingExpenses() float64 {
	if o == nil || o.OperatingExpenses == nil {
		var ret float64
		return ret
	}
	return *o.OperatingExpenses
}

// GetOperatingExpensesOk returns a tuple with the OperatingExpenses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetOperatingExpensesOk() (*float64, bool) {
	if o == nil || o.OperatingExpenses == nil {
		return nil, false
	}
	return o.OperatingExpenses, true
}

// HasOperatingExpenses returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasOperatingExpenses() bool {
	if o != nil && o.OperatingExpenses != nil {
		return true
	}

	return false
}

// SetOperatingExpenses gets a reference to the given float64 and assigns it to the OperatingExpenses field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetOperatingExpenses(v float64) {
	o.OperatingExpenses = &v
}

// GetOperatingExpensesGrowthAnnual returns the OperatingExpensesGrowthAnnual field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetOperatingExpensesGrowthAnnual() float64 {
	if o == nil || o.OperatingExpensesGrowthAnnual == nil {
		var ret float64
		return ret
	}
	return *o.OperatingExpensesGrowthAnnual
}

// GetOperatingExpensesGrowthAnnualOk returns a tuple with the OperatingExpensesGrowthAnnual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetOperatingExpensesGrowthAnnualOk() (*float64, bool) {
	if o == nil || o.OperatingExpensesGrowthAnnual == nil {
		return nil, false
	}
	return o.OperatingExpensesGrowthAnnual, true
}

// HasOperatingExpensesGrowthAnnual returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasOperatingExpensesGrowthAnnual() bool {
	if o != nil && o.OperatingExpensesGrowthAnnual != nil {
		return true
	}

	return false
}

// SetOperatingExpensesGrowthAnnual gets a reference to the given float64 and assigns it to the OperatingExpensesGrowthAnnual field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetOperatingExpensesGrowthAnnual(v float64) {
	o.OperatingExpensesGrowthAnnual = &v
}

// GetOperatingExpensesStableYears returns the OperatingExpensesStableYears field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetOperatingExpensesStableYears() float64 {
	if o == nil || o.OperatingExpensesStableYears == nil {
		var ret float64
		return ret
	}
	return *o.OperatingExpensesStableYears
}

// GetOperatingExpensesStableYearsOk returns a tuple with the OperatingExpensesStableYears field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetOperatingExpensesStableYearsOk() (*float64, bool) {
	if o == nil || o.OperatingExpensesStableYears == nil {
		return nil, false
	}
	return o.OperatingExpensesStableYears, true
}

// HasOperatingExpensesStableYears returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasOperatingExpensesStableYears() bool {
	if o != nil && o.OperatingExpensesStableYears != nil {
		return true
	}

	return false
}

// SetOperatingExpensesStableYears gets a reference to the given float64 and assigns it to the OperatingExpensesStableYears field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetOperatingExpensesStableYears(v float64) {
	o.OperatingExpensesStableYears = &v
}

// GetOperatingExpensesGrowthYears returns the OperatingExpensesGrowthYears field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetOperatingExpensesGrowthYears() float64 {
	if o == nil || o.OperatingExpensesGrowthYears == nil {
		var ret float64
		return ret
	}
	return *o.OperatingExpensesGrowthYears
}

// GetOperatingExpensesGrowthYearsOk returns a tuple with the OperatingExpensesGrowthYears field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetOperatingExpensesGrowthYearsOk() (*float64, bool) {
	if o == nil || o.OperatingExpensesGrowthYears == nil {
		return nil, false
	}
	return o.OperatingExpensesGrowthYears, true
}

// HasOperatingExpensesGrowthYears returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasOperatingExpensesGrowthYears() bool {
	if o != nil && o.OperatingExpensesGrowthYears != nil {
		return true
	}

	return false
}

// SetOperatingExpensesGrowthYears gets a reference to the given float64 and assigns it to the OperatingExpensesGrowthYears field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetOperatingExpensesGrowthYears(v float64) {
	o.OperatingExpensesGrowthYears = &v
}

// GetMedian2yrNetIncome returns the Median2yrNetIncome field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetMedian2yrNetIncome() float64 {
	if o == nil || o.Median2yrNetIncome == nil {
		var ret float64
		return ret
	}
	return *o.Median2yrNetIncome
}

// GetMedian2yrNetIncomeOk returns a tuple with the Median2yrNetIncome field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetMedian2yrNetIncomeOk() (*float64, bool) {
	if o == nil || o.Median2yrNetIncome == nil {
		return nil, false
	}
	return o.Median2yrNetIncome, true
}

// HasMedian2yrNetIncome returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasMedian2yrNetIncome() bool {
	if o != nil && o.Median2yrNetIncome != nil {
		return true
	}

	return false
}

// SetMedian2yrNetIncome gets a reference to the given float64 and assigns it to the Median2yrNetIncome field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetMedian2yrNetIncome(v float64) {
	o.Median2yrNetIncome = &v
}

// GetCapex returns the Capex field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCapex() float64 {
	if o == nil || o.Capex == nil {
		var ret float64
		return ret
	}
	return *o.Capex
}

// GetCapexOk returns a tuple with the Capex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCapexOk() (*float64, bool) {
	if o == nil || o.Capex == nil {
		return nil, false
	}
	return o.Capex, true
}

// HasCapex returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasCapex() bool {
	if o != nil && o.Capex != nil {
		return true
	}

	return false
}

// SetCapex gets a reference to the given float64 and assigns it to the Capex field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetCapex(v float64) {
	o.Capex = &v
}

// GetCapexGrowth1y returns the CapexGrowth1y field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCapexGrowth1y() float64 {
	if o == nil || o.CapexGrowth1y == nil {
		var ret float64
		return ret
	}
	return *o.CapexGrowth1y
}

// GetCapexGrowth1yOk returns a tuple with the CapexGrowth1y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCapexGrowth1yOk() (*float64, bool) {
	if o == nil || o.CapexGrowth1y == nil {
		return nil, false
	}
	return o.CapexGrowth1y, true
}

// HasCapexGrowth1y returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasCapexGrowth1y() bool {
	if o != nil && o.CapexGrowth1y != nil {
		return true
	}

	return false
}

// SetCapexGrowth1y gets a reference to the given float64 and assigns it to the CapexGrowth1y field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetCapexGrowth1y(v float64) {
	o.CapexGrowth1y = &v
}

// GetCapexGrowthAnnual returns the CapexGrowthAnnual field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCapexGrowthAnnual() float64 {
	if o == nil || o.CapexGrowthAnnual == nil {
		var ret float64
		return ret
	}
	return *o.CapexGrowthAnnual
}

// GetCapexGrowthAnnualOk returns a tuple with the CapexGrowthAnnual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCapexGrowthAnnualOk() (*float64, bool) {
	if o == nil || o.CapexGrowthAnnual == nil {
		return nil, false
	}
	return o.CapexGrowthAnnual, true
}

// HasCapexGrowthAnnual returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasCapexGrowthAnnual() bool {
	if o != nil && o.CapexGrowthAnnual != nil {
		return true
	}

	return false
}

// SetCapexGrowthAnnual gets a reference to the given float64 and assigns it to the CapexGrowthAnnual field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetCapexGrowthAnnual(v float64) {
	o.CapexGrowthAnnual = &v
}

// GetNetDebt returns the NetDebt field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetNetDebt() float64 {
	if o == nil || o.NetDebt == nil {
		var ret float64
		return ret
	}
	return *o.NetDebt
}

// GetNetDebtOk returns a tuple with the NetDebt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetNetDebtOk() (*float64, bool) {
	if o == nil || o.NetDebt == nil {
		return nil, false
	}
	return o.NetDebt, true
}

// HasNetDebt returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasNetDebt() bool {
	if o != nil && o.NetDebt != nil {
		return true
	}

	return false
}

// SetNetDebt gets a reference to the given float64 and assigns it to the NetDebt field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetNetDebt(v float64) {
	o.NetDebt = &v
}

// GetManagementRateReturn returns the ManagementRateReturn field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetManagementRateReturn() float64 {
	if o == nil || o.ManagementRateReturn == nil {
		var ret float64
		return ret
	}
	return *o.ManagementRateReturn
}

// GetManagementRateReturnOk returns a tuple with the ManagementRateReturn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetManagementRateReturnOk() (*float64, bool) {
	if o == nil || o.ManagementRateReturn == nil {
		return nil, false
	}
	return o.ManagementRateReturn, true
}

// HasManagementRateReturn returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasManagementRateReturn() bool {
	if o != nil && o.ManagementRateReturn != nil {
		return true
	}

	return false
}

// SetManagementRateReturn gets a reference to the given float64 and assigns it to the ManagementRateReturn field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetManagementRateReturn(v float64) {
	o.ManagementRateReturn = &v
}

// GetBookValuePerShare returns the BookValuePerShare field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetBookValuePerShare() float64 {
	if o == nil || o.BookValuePerShare == nil {
		var ret float64
		return ret
	}
	return *o.BookValuePerShare
}

// GetBookValuePerShareOk returns a tuple with the BookValuePerShare field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetBookValuePerShareOk() (*float64, bool) {
	if o == nil || o.BookValuePerShare == nil {
		return nil, false
	}
	return o.BookValuePerShare, true
}

// HasBookValuePerShare returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasBookValuePerShare() bool {
	if o != nil && o.BookValuePerShare != nil {
		return true
	}

	return false
}

// SetBookValuePerShare gets a reference to the given float64 and assigns it to the BookValuePerShare field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetBookValuePerShare(v float64) {
	o.BookValuePerShare = &v
}

// GetLeveredFreeCashFlow returns the LeveredFreeCashFlow field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashFlow() float64 {
	if o == nil || o.LeveredFreeCashFlow == nil {
		var ret float64
		return ret
	}
	return *o.LeveredFreeCashFlow
}

// GetLeveredFreeCashFlowOk returns a tuple with the LeveredFreeCashFlow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashFlowOk() (*float64, bool) {
	if o == nil || o.LeveredFreeCashFlow == nil {
		return nil, false
	}
	return o.LeveredFreeCashFlow, true
}

// HasLeveredFreeCashFlow returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasLeveredFreeCashFlow() bool {
	if o != nil && o.LeveredFreeCashFlow != nil {
		return true
	}

	return false
}

// SetLeveredFreeCashFlow gets a reference to the given float64 and assigns it to the LeveredFreeCashFlow field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetLeveredFreeCashFlow(v float64) {
	o.LeveredFreeCashFlow = &v
}

// GetLeveredFreeCashFlow1y returns the LeveredFreeCashFlow1y field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashFlow1y() float64 {
	if o == nil || o.LeveredFreeCashFlow1y == nil {
		var ret float64
		return ret
	}
	return *o.LeveredFreeCashFlow1y
}

// GetLeveredFreeCashFlow1yOk returns a tuple with the LeveredFreeCashFlow1y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashFlow1yOk() (*float64, bool) {
	if o == nil || o.LeveredFreeCashFlow1y == nil {
		return nil, false
	}
	return o.LeveredFreeCashFlow1y, true
}

// HasLeveredFreeCashFlow1y returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasLeveredFreeCashFlow1y() bool {
	if o != nil && o.LeveredFreeCashFlow1y != nil {
		return true
	}

	return false
}

// SetLeveredFreeCashFlow1y gets a reference to the given float64 and assigns it to the LeveredFreeCashFlow1y field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetLeveredFreeCashFlow1y(v float64) {
	o.LeveredFreeCashFlow1y = &v
}

// GetLeveredFreeCashFlow2y returns the LeveredFreeCashFlow2y field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashFlow2y() float64 {
	if o == nil || o.LeveredFreeCashFlow2y == nil {
		var ret float64
		return ret
	}
	return *o.LeveredFreeCashFlow2y
}

// GetLeveredFreeCashFlow2yOk returns a tuple with the LeveredFreeCashFlow2y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashFlow2yOk() (*float64, bool) {
	if o == nil || o.LeveredFreeCashFlow2y == nil {
		return nil, false
	}
	return o.LeveredFreeCashFlow2y, true
}

// HasLeveredFreeCashFlow2y returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasLeveredFreeCashFlow2y() bool {
	if o != nil && o.LeveredFreeCashFlow2y != nil {
		return true
	}

	return false
}

// SetLeveredFreeCashFlow2y gets a reference to the given float64 and assigns it to the LeveredFreeCashFlow2y field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetLeveredFreeCashFlow2y(v float64) {
	o.LeveredFreeCashFlow2y = &v
}

// GetLeveredFreeCashGrowthAnnual returns the LeveredFreeCashGrowthAnnual field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashGrowthAnnual() float64 {
	if o == nil || o.LeveredFreeCashGrowthAnnual == nil {
		var ret float64
		return ret
	}
	return *o.LeveredFreeCashGrowthAnnual
}

// GetLeveredFreeCashGrowthAnnualOk returns a tuple with the LeveredFreeCashGrowthAnnual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashGrowthAnnualOk() (*float64, bool) {
	if o == nil || o.LeveredFreeCashGrowthAnnual == nil {
		return nil, false
	}
	return o.LeveredFreeCashGrowthAnnual, true
}

// HasLeveredFreeCashGrowthAnnual returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasLeveredFreeCashGrowthAnnual() bool {
	if o != nil && o.LeveredFreeCashGrowthAnnual != nil {
		return true
	}

	return false
}

// SetLeveredFreeCashGrowthAnnual gets a reference to the given float64 and assigns it to the LeveredFreeCashGrowthAnnual field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetLeveredFreeCashGrowthAnnual(v float64) {
	o.LeveredFreeCashGrowthAnnual = &v
}

// GetLeveredFreeCashFlowGrowthAnnual returns the LeveredFreeCashFlowGrowthAnnual field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashFlowGrowthAnnual() float64 {
	if o == nil || o.LeveredFreeCashFlowGrowthAnnual == nil {
		var ret float64
		return ret
	}
	return *o.LeveredFreeCashFlowGrowthAnnual
}

// GetLeveredFreeCashFlowGrowthAnnualOk returns a tuple with the LeveredFreeCashFlowGrowthAnnual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashFlowGrowthAnnualOk() (*float64, bool) {
	if o == nil || o.LeveredFreeCashFlowGrowthAnnual == nil {
		return nil, false
	}
	return o.LeveredFreeCashFlowGrowthAnnual, true
}

// HasLeveredFreeCashFlowGrowthAnnual returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasLeveredFreeCashFlowGrowthAnnual() bool {
	if o != nil && o.LeveredFreeCashFlowGrowthAnnual != nil {
		return true
	}

	return false
}

// SetLeveredFreeCashFlowGrowthAnnual gets a reference to the given float64 and assigns it to the LeveredFreeCashFlowGrowthAnnual field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetLeveredFreeCashFlowGrowthAnnual(v float64) {
	o.LeveredFreeCashFlowGrowthAnnual = &v
}

// GetLeveredFreeCashFlowGrowthYears returns the LeveredFreeCashFlowGrowthYears field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashFlowGrowthYears() float64 {
	if o == nil || o.LeveredFreeCashFlowGrowthYears == nil {
		var ret float64
		return ret
	}
	return *o.LeveredFreeCashFlowGrowthYears
}

// GetLeveredFreeCashFlowGrowthYearsOk returns a tuple with the LeveredFreeCashFlowGrowthYears field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashFlowGrowthYearsOk() (*float64, bool) {
	if o == nil || o.LeveredFreeCashFlowGrowthYears == nil {
		return nil, false
	}
	return o.LeveredFreeCashFlowGrowthYears, true
}

// HasLeveredFreeCashFlowGrowthYears returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasLeveredFreeCashFlowGrowthYears() bool {
	if o != nil && o.LeveredFreeCashFlowGrowthYears != nil {
		return true
	}

	return false
}

// SetLeveredFreeCashFlowGrowthYears gets a reference to the given float64 and assigns it to the LeveredFreeCashFlowGrowthYears field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetLeveredFreeCashFlowGrowthYears(v float64) {
	o.LeveredFreeCashFlowGrowthYears = &v
}

// GetLeveredFreeCashFlowStableYears returns the LeveredFreeCashFlowStableYears field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashFlowStableYears() float64 {
	if o == nil || o.LeveredFreeCashFlowStableYears == nil {
		var ret float64
		return ret
	}
	return *o.LeveredFreeCashFlowStableYears
}

// GetLeveredFreeCashFlowStableYearsOk returns a tuple with the LeveredFreeCashFlowStableYears field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashFlowStableYearsOk() (*float64, bool) {
	if o == nil || o.LeveredFreeCashFlowStableYears == nil {
		return nil, false
	}
	return o.LeveredFreeCashFlowStableYears, true
}

// HasLeveredFreeCashFlowStableYears returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasLeveredFreeCashFlowStableYears() bool {
	if o != nil && o.LeveredFreeCashFlowStableYears != nil {
		return true
	}

	return false
}

// SetLeveredFreeCashFlowStableYears gets a reference to the given float64 and assigns it to the LeveredFreeCashFlowStableYears field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetLeveredFreeCashFlowStableYears(v float64) {
	o.LeveredFreeCashFlowStableYears = &v
}

// GetCashFromInvesting returns the CashFromInvesting field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCashFromInvesting() float64 {
	if o == nil || o.CashFromInvesting == nil {
		var ret float64
		return ret
	}
	return *o.CashFromInvesting
}

// GetCashFromInvestingOk returns a tuple with the CashFromInvesting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCashFromInvestingOk() (*float64, bool) {
	if o == nil || o.CashFromInvesting == nil {
		return nil, false
	}
	return o.CashFromInvesting, true
}

// HasCashFromInvesting returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasCashFromInvesting() bool {
	if o != nil && o.CashFromInvesting != nil {
		return true
	}

	return false
}

// SetCashFromInvesting gets a reference to the given float64 and assigns it to the CashFromInvesting field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetCashFromInvesting(v float64) {
	o.CashFromInvesting = &v
}

// GetNetDebtToEbitda returns the NetDebtToEbitda field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetNetDebtToEbitda() float64 {
	if o == nil || o.NetDebtToEbitda == nil {
		var ret float64
		return ret
	}
	return *o.NetDebtToEbitda
}

// GetNetDebtToEbitdaOk returns a tuple with the NetDebtToEbitda field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetNetDebtToEbitdaOk() (*float64, bool) {
	if o == nil || o.NetDebtToEbitda == nil {
		return nil, false
	}
	return o.NetDebtToEbitda, true
}

// HasNetDebtToEbitda returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasNetDebtToEbitda() bool {
	if o != nil && o.NetDebtToEbitda != nil {
		return true
	}

	return false
}

// SetNetDebtToEbitda gets a reference to the given float64 and assigns it to the NetDebtToEbitda field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetNetDebtToEbitda(v float64) {
	o.NetDebtToEbitda = &v
}

// GetCapitalisationPercent returns the CapitalisationPercent field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCapitalisationPercent() float64 {
	if o == nil || o.CapitalisationPercent == nil {
		var ret float64
		return ret
	}
	return *o.CapitalisationPercent
}

// GetCapitalisationPercentOk returns a tuple with the CapitalisationPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCapitalisationPercentOk() (*float64, bool) {
	if o == nil || o.CapitalisationPercent == nil {
		return nil, false
	}
	return o.CapitalisationPercent, true
}

// HasCapitalisationPercent returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasCapitalisationPercent() bool {
	if o != nil && o.CapitalisationPercent != nil {
		return true
	}

	return false
}

// SetCapitalisationPercent gets a reference to the given float64 and assigns it to the CapitalisationPercent field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetCapitalisationPercent(v float64) {
	o.CapitalisationPercent = &v
}

// GetCapitalisationPercent1y returns the CapitalisationPercent1y field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCapitalisationPercent1y() float64 {
	if o == nil || o.CapitalisationPercent1y == nil {
		var ret float64
		return ret
	}
	return *o.CapitalisationPercent1y
}

// GetCapitalisationPercent1yOk returns a tuple with the CapitalisationPercent1y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCapitalisationPercent1yOk() (*float64, bool) {
	if o == nil || o.CapitalisationPercent1y == nil {
		return nil, false
	}
	return o.CapitalisationPercent1y, true
}

// HasCapitalisationPercent1y returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasCapitalisationPercent1y() bool {
	if o != nil && o.CapitalisationPercent1y != nil {
		return true
	}

	return false
}

// SetCapitalisationPercent1y gets a reference to the given float64 and assigns it to the CapitalisationPercent1y field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetCapitalisationPercent1y(v float64) {
	o.CapitalisationPercent1y = &v
}

// GetCashOperatingGrowth1y returns the CashOperatingGrowth1y field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCashOperatingGrowth1y() float64 {
	if o == nil || o.CashOperatingGrowth1y == nil {
		var ret float64
		return ret
	}
	return *o.CashOperatingGrowth1y
}

// GetCashOperatingGrowth1yOk returns a tuple with the CashOperatingGrowth1y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCashOperatingGrowth1yOk() (*float64, bool) {
	if o == nil || o.CashOperatingGrowth1y == nil {
		return nil, false
	}
	return o.CashOperatingGrowth1y, true
}

// HasCashOperatingGrowth1y returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasCashOperatingGrowth1y() bool {
	if o != nil && o.CashOperatingGrowth1y != nil {
		return true
	}

	return false
}

// SetCashOperatingGrowth1y gets a reference to the given float64 and assigns it to the CashOperatingGrowth1y field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetCashOperatingGrowth1y(v float64) {
	o.CashOperatingGrowth1y = &v
}

// GetCashFromInvesting1y returns the CashFromInvesting1y field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCashFromInvesting1y() float64 {
	if o == nil || o.CashFromInvesting1y == nil {
		var ret float64
		return ret
	}
	return *o.CashFromInvesting1y
}

// GetCashFromInvesting1yOk returns a tuple with the CashFromInvesting1y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCashFromInvesting1yOk() (*float64, bool) {
	if o == nil || o.CashFromInvesting1y == nil {
		return nil, false
	}
	return o.CashFromInvesting1y, true
}

// HasCashFromInvesting1y returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasCashFromInvesting1y() bool {
	if o != nil && o.CashFromInvesting1y != nil {
		return true
	}

	return false
}

// SetCashFromInvesting1y gets a reference to the given float64 and assigns it to the CashFromInvesting1y field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetCashFromInvesting1y(v float64) {
	o.CashFromInvesting1y = &v
}

// GetInventoryGrowth1y returns the InventoryGrowth1y field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetInventoryGrowth1y() float64 {
	if o == nil || o.InventoryGrowth1y == nil {
		var ret float64
		return ret
	}
	return *o.InventoryGrowth1y
}

// GetInventoryGrowth1yOk returns a tuple with the InventoryGrowth1y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetInventoryGrowth1yOk() (*float64, bool) {
	if o == nil || o.InventoryGrowth1y == nil {
		return nil, false
	}
	return o.InventoryGrowth1y, true
}

// HasInventoryGrowth1y returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasInventoryGrowth1y() bool {
	if o != nil && o.InventoryGrowth1y != nil {
		return true
	}

	return false
}

// SetInventoryGrowth1y gets a reference to the given float64 and assigns it to the InventoryGrowth1y field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetInventoryGrowth1y(v float64) {
	o.InventoryGrowth1y = &v
}

// GetNetOperatingAssets returns the NetOperatingAssets field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetNetOperatingAssets() float64 {
	if o == nil || o.NetOperatingAssets == nil {
		var ret float64
		return ret
	}
	return *o.NetOperatingAssets
}

// GetNetOperatingAssetsOk returns a tuple with the NetOperatingAssets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetNetOperatingAssetsOk() (*float64, bool) {
	if o == nil || o.NetOperatingAssets == nil {
		return nil, false
	}
	return o.NetOperatingAssets, true
}

// HasNetOperatingAssets returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasNetOperatingAssets() bool {
	if o != nil && o.NetOperatingAssets != nil {
		return true
	}

	return false
}

// SetNetOperatingAssets gets a reference to the given float64 and assigns it to the NetOperatingAssets field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetNetOperatingAssets(v float64) {
	o.NetOperatingAssets = &v
}

// GetNetOperatingAssets1y returns the NetOperatingAssets1y field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetNetOperatingAssets1y() float64 {
	if o == nil || o.NetOperatingAssets1y == nil {
		var ret float64
		return ret
	}
	return *o.NetOperatingAssets1y
}

// GetNetOperatingAssets1yOk returns a tuple with the NetOperatingAssets1y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetNetOperatingAssets1yOk() (*float64, bool) {
	if o == nil || o.NetOperatingAssets1y == nil {
		return nil, false
	}
	return o.NetOperatingAssets1y, true
}

// HasNetOperatingAssets1y returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasNetOperatingAssets1y() bool {
	if o != nil && o.NetOperatingAssets1y != nil {
		return true
	}

	return false
}

// SetNetOperatingAssets1y gets a reference to the given float64 and assigns it to the NetOperatingAssets1y field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetNetOperatingAssets1y(v float64) {
	o.NetOperatingAssets1y = &v
}

// GetAggregateAccruals returns the AggregateAccruals field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetAggregateAccruals() float64 {
	if o == nil || o.AggregateAccruals == nil {
		var ret float64
		return ret
	}
	return *o.AggregateAccruals
}

// GetAggregateAccrualsOk returns a tuple with the AggregateAccruals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetAggregateAccrualsOk() (*float64, bool) {
	if o == nil || o.AggregateAccruals == nil {
		return nil, false
	}
	return o.AggregateAccruals, true
}

// HasAggregateAccruals returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasAggregateAccruals() bool {
	if o != nil && o.AggregateAccruals != nil {
		return true
	}

	return false
}

// SetAggregateAccruals gets a reference to the given float64 and assigns it to the AggregateAccruals field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetAggregateAccruals(v float64) {
	o.AggregateAccruals = &v
}

// GetAccountsReceivableGrowth1y returns the AccountsReceivableGrowth1y field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetAccountsReceivableGrowth1y() float64 {
	if o == nil || o.AccountsReceivableGrowth1y == nil {
		var ret float64
		return ret
	}
	return *o.AccountsReceivableGrowth1y
}

// GetAccountsReceivableGrowth1yOk returns a tuple with the AccountsReceivableGrowth1y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetAccountsReceivableGrowth1yOk() (*float64, bool) {
	if o == nil || o.AccountsReceivableGrowth1y == nil {
		return nil, false
	}
	return o.AccountsReceivableGrowth1y, true
}

// HasAccountsReceivableGrowth1y returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasAccountsReceivableGrowth1y() bool {
	if o != nil && o.AccountsReceivableGrowth1y != nil {
		return true
	}

	return false
}

// SetAccountsReceivableGrowth1y gets a reference to the given float64 and assigns it to the AccountsReceivableGrowth1y field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetAccountsReceivableGrowth1y(v float64) {
	o.AccountsReceivableGrowth1y = &v
}

// GetAccountsReceivablePercent returns the AccountsReceivablePercent field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetAccountsReceivablePercent() float64 {
	if o == nil || o.AccountsReceivablePercent == nil {
		var ret float64
		return ret
	}
	return *o.AccountsReceivablePercent
}

// GetAccountsReceivablePercentOk returns a tuple with the AccountsReceivablePercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetAccountsReceivablePercentOk() (*float64, bool) {
	if o == nil || o.AccountsReceivablePercent == nil {
		return nil, false
	}
	return o.AccountsReceivablePercent, true
}

// HasAccountsReceivablePercent returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasAccountsReceivablePercent() bool {
	if o != nil && o.AccountsReceivablePercent != nil {
		return true
	}

	return false
}

// SetAccountsReceivablePercent gets a reference to the given float64 and assigns it to the AccountsReceivablePercent field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetAccountsReceivablePercent(v float64) {
	o.AccountsReceivablePercent = &v
}

// GetLongTermAssets returns the LongTermAssets field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLongTermAssets() float64 {
	if o == nil || o.LongTermAssets == nil {
		var ret float64
		return ret
	}
	return *o.LongTermAssets
}

// GetLongTermAssetsOk returns a tuple with the LongTermAssets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLongTermAssetsOk() (*float64, bool) {
	if o == nil || o.LongTermAssets == nil {
		return nil, false
	}
	return o.LongTermAssets, true
}

// HasLongTermAssets returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasLongTermAssets() bool {
	if o != nil && o.LongTermAssets != nil {
		return true
	}

	return false
}

// SetLongTermAssets gets a reference to the given float64 and assigns it to the LongTermAssets field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetLongTermAssets(v float64) {
	o.LongTermAssets = &v
}

// GetLastBalanceSheetUpdate returns the LastBalanceSheetUpdate field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLastBalanceSheetUpdate() float64 {
	if o == nil || o.LastBalanceSheetUpdate == nil {
		var ret float64
		return ret
	}
	return *o.LastBalanceSheetUpdate
}

// GetLastBalanceSheetUpdateOk returns a tuple with the LastBalanceSheetUpdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLastBalanceSheetUpdateOk() (*float64, bool) {
	if o == nil || o.LastBalanceSheetUpdate == nil {
		return nil, false
	}
	return o.LastBalanceSheetUpdate, true
}

// HasLastBalanceSheetUpdate returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasLastBalanceSheetUpdate() bool {
	if o != nil && o.LastBalanceSheetUpdate != nil {
		return true
	}

	return false
}

// SetLastBalanceSheetUpdate gets a reference to the given float64 and assigns it to the LastBalanceSheetUpdate field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetLastBalanceSheetUpdate(v float64) {
	o.LastBalanceSheetUpdate = &v
}

// GetCurrentPortionLeaseLiabilities returns the CurrentPortionLeaseLiabilities field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCurrentPortionLeaseLiabilities() float64 {
	if o == nil || o.CurrentPortionLeaseLiabilities == nil {
		var ret float64
		return ret
	}
	return *o.CurrentPortionLeaseLiabilities
}

// GetCurrentPortionLeaseLiabilitiesOk returns a tuple with the CurrentPortionLeaseLiabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetCurrentPortionLeaseLiabilitiesOk() (*float64, bool) {
	if o == nil || o.CurrentPortionLeaseLiabilities == nil {
		return nil, false
	}
	return o.CurrentPortionLeaseLiabilities, true
}

// HasCurrentPortionLeaseLiabilities returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasCurrentPortionLeaseLiabilities() bool {
	if o != nil && o.CurrentPortionLeaseLiabilities != nil {
		return true
	}

	return false
}

// SetCurrentPortionLeaseLiabilities gets a reference to the given float64 and assigns it to the CurrentPortionLeaseLiabilities field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetCurrentPortionLeaseLiabilities(v float64) {
	o.CurrentPortionLeaseLiabilities = &v
}

// GetLongTermPortionLeaseLiabilities returns the LongTermPortionLeaseLiabilities field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLongTermPortionLeaseLiabilities() float64 {
	if o == nil || o.LongTermPortionLeaseLiabilities == nil {
		var ret float64
		return ret
	}
	return *o.LongTermPortionLeaseLiabilities
}

// GetLongTermPortionLeaseLiabilitiesOk returns a tuple with the LongTermPortionLeaseLiabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLongTermPortionLeaseLiabilitiesOk() (*float64, bool) {
	if o == nil || o.LongTermPortionLeaseLiabilities == nil {
		return nil, false
	}
	return o.LongTermPortionLeaseLiabilities, true
}

// HasLongTermPortionLeaseLiabilities returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasLongTermPortionLeaseLiabilities() bool {
	if o != nil && o.LongTermPortionLeaseLiabilities != nil {
		return true
	}

	return false
}

// SetLongTermPortionLeaseLiabilities gets a reference to the given float64 and assigns it to the LongTermPortionLeaseLiabilities field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetLongTermPortionLeaseLiabilities(v float64) {
	o.LongTermPortionLeaseLiabilities = &v
}

// GetTotalLeaseLiabilities returns the TotalLeaseLiabilities field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalLeaseLiabilities() float64 {
	if o == nil || o.TotalLeaseLiabilities == nil {
		var ret float64
		return ret
	}
	return *o.TotalLeaseLiabilities
}

// GetTotalLeaseLiabilitiesOk returns a tuple with the TotalLeaseLiabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetTotalLeaseLiabilitiesOk() (*float64, bool) {
	if o == nil || o.TotalLeaseLiabilities == nil {
		return nil, false
	}
	return o.TotalLeaseLiabilities, true
}

// HasTotalLeaseLiabilities returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasTotalLeaseLiabilities() bool {
	if o != nil && o.TotalLeaseLiabilities != nil {
		return true
	}

	return false
}

// SetTotalLeaseLiabilities gets a reference to the given float64 and assigns it to the TotalLeaseLiabilities field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetTotalLeaseLiabilities(v float64) {
	o.TotalLeaseLiabilities = &v
}

// GetRestrictedCash returns the RestrictedCash field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetRestrictedCash() float64 {
	if o == nil || o.RestrictedCash == nil {
		var ret float64
		return ret
	}
	return *o.RestrictedCash
}

// GetRestrictedCashOk returns a tuple with the RestrictedCash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetRestrictedCashOk() (*float64, bool) {
	if o == nil || o.RestrictedCash == nil {
		return nil, false
	}
	return o.RestrictedCash, true
}

// HasRestrictedCash returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasRestrictedCash() bool {
	if o != nil && o.RestrictedCash != nil {
		return true
	}

	return false
}

// SetRestrictedCash gets a reference to the given float64 and assigns it to the RestrictedCash field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetRestrictedCash(v float64) {
	o.RestrictedCash = &v
}

// GetRestrictedCashRatio returns the RestrictedCashRatio field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetRestrictedCashRatio() float64 {
	if o == nil || o.RestrictedCashRatio == nil {
		var ret float64
		return ret
	}
	return *o.RestrictedCashRatio
}

// GetRestrictedCashRatioOk returns a tuple with the RestrictedCashRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetRestrictedCashRatioOk() (*float64, bool) {
	if o == nil || o.RestrictedCashRatio == nil {
		return nil, false
	}
	return o.RestrictedCashRatio, true
}

// HasRestrictedCashRatio returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasRestrictedCashRatio() bool {
	if o != nil && o.RestrictedCashRatio != nil {
		return true
	}

	return false
}

// SetRestrictedCashRatio gets a reference to the given float64 and assigns it to the RestrictedCashRatio field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetRestrictedCashRatio(v float64) {
	o.RestrictedCashRatio = &v
}

// GetLeveredFreeCashFlowBreakEvenYears returns the LeveredFreeCashFlowBreakEvenYears field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashFlowBreakEvenYears() float64 {
	if o == nil || o.LeveredFreeCashFlowBreakEvenYears == nil {
		var ret float64
		return ret
	}
	return *o.LeveredFreeCashFlowBreakEvenYears
}

// GetLeveredFreeCashFlowBreakEvenYearsOk returns a tuple with the LeveredFreeCashFlowBreakEvenYears field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) GetLeveredFreeCashFlowBreakEvenYearsOk() (*float64, bool) {
	if o == nil || o.LeveredFreeCashFlowBreakEvenYears == nil {
		return nil, false
	}
	return o.LeveredFreeCashFlowBreakEvenYears, true
}

// HasLeveredFreeCashFlowBreakEvenYears returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedAnalysisHealth) HasLeveredFreeCashFlowBreakEvenYears() bool {
	if o != nil && o.LeveredFreeCashFlowBreakEvenYears != nil {
		return true
	}

	return false
}

// SetLeveredFreeCashFlowBreakEvenYears gets a reference to the given float64 and assigns it to the LeveredFreeCashFlowBreakEvenYears field.
func (o *CompanyAnalysisExtendedAnalysisHealth) SetLeveredFreeCashFlowBreakEvenYears(v float64) {
	o.LeveredFreeCashFlowBreakEvenYears = &v
}

func (o CompanyAnalysisExtendedAnalysisHealth) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.NetIncome != nil {
		toSerialize["net_income"] = o.NetIncome
	}
	if o.NetInterestExpense != nil {
		toSerialize["net_interest_expense"] = o.NetInterestExpense
	}
	if o.CashOperating != nil {
		toSerialize["cash_operating"] = o.CashOperating
	}
	if o.TotalAssets != nil {
		toSerialize["total_assets"] = o.TotalAssets
	}
	if o.Ppe != nil {
		toSerialize["ppe"] = o.Ppe
	}
	if o.Inventory != nil {
		toSerialize["inventory"] = o.Inventory
	}
	if o.CashStInvestments != nil {
		toSerialize["cash_st_investments"] = o.CashStInvestments
	}
	if o.Receivables != nil {
		toSerialize["receivables"] = o.Receivables
	}
	if o.CurrentAssets != nil {
		toSerialize["current_assets"] = o.CurrentAssets
	}
	if o.TotalEquity != nil {
		toSerialize["total_equity"] = o.TotalEquity
	}
	if o.TotalDebt != nil {
		toSerialize["total_debt"] = o.TotalDebt
	}
	if o.LongTermDebt != nil {
		toSerialize["long_term_debt"] = o.LongTermDebt
	}
	if o.LongTermLiab != nil {
		toSerialize["long_term_liab"] = o.LongTermLiab
	}
	if o.AccountsPayable != nil {
		toSerialize["accounts_payable"] = o.AccountsPayable
	}
	if o.TotalCurrentLiab != nil {
		toSerialize["total_current_liab"] = o.TotalCurrentLiab
	}
	if o.TotalLiabEquity != nil {
		toSerialize["total_liab_equity"] = o.TotalLiabEquity
	}
	if o.TotalDebtEquity != nil {
		toSerialize["total_debt_equity"] = o.TotalDebtEquity
	}
	if o.TotalInventory != nil {
		toSerialize["total_inventory"] = o.TotalInventory
	}
	if o.DebtToEquityRatio != nil {
		toSerialize["debt_to_equity_ratio"] = o.DebtToEquityRatio
	}
	if o.DebtToEquityRatioPast != nil {
		toSerialize["debt_to_equity_ratio_past"] = o.DebtToEquityRatioPast
	}
	if o.AssetsEquityRatio != nil {
		toSerialize["assets_equity_ratio"] = o.AssetsEquityRatio
	}
	if o.FixedToTotalAssets != nil {
		toSerialize["fixed_to_total_assets"] = o.FixedToTotalAssets
	}
	if o.CurrentAssetsToTotalDebt != nil {
		toSerialize["current_assets_to_total_debt"] = o.CurrentAssetsToTotalDebt
	}
	if o.OperatingCashFlowToTotalDebt != nil {
		toSerialize["operating_cash_flow_to_total_debt"] = o.OperatingCashFlowToTotalDebt
	}
	if o.NetInterestCover != nil {
		toSerialize["net_interest_cover"] = o.NetInterestCover
	}
	if o.CurrentSolvencyRatio != nil {
		toSerialize["current_solvency_ratio"] = o.CurrentSolvencyRatio
	}
	if o.CurrentAssetsToLongTermLiab != nil {
		toSerialize["current_assets_to_long_term_liab"] = o.CurrentAssetsToLongTermLiab
	}
	if o.OperatingExpenses != nil {
		toSerialize["operating_expenses"] = o.OperatingExpenses
	}
	if o.OperatingExpensesGrowthAnnual != nil {
		toSerialize["operating_expenses_growth_annual"] = o.OperatingExpensesGrowthAnnual
	}
	if o.OperatingExpensesStableYears != nil {
		toSerialize["operating_expenses_stable_years"] = o.OperatingExpensesStableYears
	}
	if o.OperatingExpensesGrowthYears != nil {
		toSerialize["operating_expenses_growth_years"] = o.OperatingExpensesGrowthYears
	}
	if o.Median2yrNetIncome != nil {
		toSerialize["median_2yr_net_income"] = o.Median2yrNetIncome
	}
	if o.Capex != nil {
		toSerialize["capex"] = o.Capex
	}
	if o.CapexGrowth1y != nil {
		toSerialize["capex_growth_1y"] = o.CapexGrowth1y
	}
	if o.CapexGrowthAnnual != nil {
		toSerialize["capex_growth_annual"] = o.CapexGrowthAnnual
	}
	if o.NetDebt != nil {
		toSerialize["net_debt"] = o.NetDebt
	}
	if o.ManagementRateReturn != nil {
		toSerialize["management_rate_return"] = o.ManagementRateReturn
	}
	if o.BookValuePerShare != nil {
		toSerialize["book_value_per_share"] = o.BookValuePerShare
	}
	if o.LeveredFreeCashFlow != nil {
		toSerialize["levered_free_cash_flow"] = o.LeveredFreeCashFlow
	}
	if o.LeveredFreeCashFlow1y != nil {
		toSerialize["levered_free_cash_flow_1y"] = o.LeveredFreeCashFlow1y
	}
	if o.LeveredFreeCashFlow2y != nil {
		toSerialize["levered_free_cash_flow_2y"] = o.LeveredFreeCashFlow2y
	}
	if o.LeveredFreeCashGrowthAnnual != nil {
		toSerialize["levered_free_cash_growth_annual"] = o.LeveredFreeCashGrowthAnnual
	}
	if o.LeveredFreeCashFlowGrowthAnnual != nil {
		toSerialize["levered_free_cash_flow_growth_annual"] = o.LeveredFreeCashFlowGrowthAnnual
	}
	if o.LeveredFreeCashFlowGrowthYears != nil {
		toSerialize["levered_free_cash_flow_growth_years"] = o.LeveredFreeCashFlowGrowthYears
	}
	if o.LeveredFreeCashFlowStableYears != nil {
		toSerialize["levered_free_cash_flow_stable_years"] = o.LeveredFreeCashFlowStableYears
	}
	if o.CashFromInvesting != nil {
		toSerialize["cash_from_investing"] = o.CashFromInvesting
	}
	if o.NetDebtToEbitda != nil {
		toSerialize["net_debt_to_ebitda"] = o.NetDebtToEbitda
	}
	if o.CapitalisationPercent != nil {
		toSerialize["capitalisation_percent"] = o.CapitalisationPercent
	}
	if o.CapitalisationPercent1y != nil {
		toSerialize["capitalisation_percent_1y"] = o.CapitalisationPercent1y
	}
	if o.CashOperatingGrowth1y != nil {
		toSerialize["cash_operating_growth_1y"] = o.CashOperatingGrowth1y
	}
	if o.CashFromInvesting1y != nil {
		toSerialize["cash_from_investing_1y"] = o.CashFromInvesting1y
	}
	if o.InventoryGrowth1y != nil {
		toSerialize["inventory_growth_1y"] = o.InventoryGrowth1y
	}
	if o.NetOperatingAssets != nil {
		toSerialize["net_operating_assets"] = o.NetOperatingAssets
	}
	if o.NetOperatingAssets1y != nil {
		toSerialize["net_operating_assets_1y"] = o.NetOperatingAssets1y
	}
	if o.AggregateAccruals != nil {
		toSerialize["aggregate_accruals"] = o.AggregateAccruals
	}
	if o.AccountsReceivableGrowth1y != nil {
		toSerialize["accounts_receivable_growth_1y"] = o.AccountsReceivableGrowth1y
	}
	if o.AccountsReceivablePercent != nil {
		toSerialize["accounts_receivable_percent"] = o.AccountsReceivablePercent
	}
	if o.LongTermAssets != nil {
		toSerialize["long_term_assets"] = o.LongTermAssets
	}
	if o.LastBalanceSheetUpdate != nil {
		toSerialize["last_balance_sheet_update"] = o.LastBalanceSheetUpdate
	}
	if o.CurrentPortionLeaseLiabilities != nil {
		toSerialize["current_portion_lease_liabilities"] = o.CurrentPortionLeaseLiabilities
	}
	if o.LongTermPortionLeaseLiabilities != nil {
		toSerialize["long_term_portion_lease_liabilities"] = o.LongTermPortionLeaseLiabilities
	}
	if o.TotalLeaseLiabilities != nil {
		toSerialize["total_lease_liabilities"] = o.TotalLeaseLiabilities
	}
	if o.RestrictedCash != nil {
		toSerialize["restricted_cash"] = o.RestrictedCash
	}
	if o.RestrictedCashRatio != nil {
		toSerialize["restricted_cash_ratio"] = o.RestrictedCashRatio
	}
	if o.LeveredFreeCashFlowBreakEvenYears != nil {
		toSerialize["levered_free_cash_flow_break_even_years"] = o.LeveredFreeCashFlowBreakEvenYears
	}
	return json.Marshal(toSerialize)
}

type NullableCompanyAnalysisExtendedAnalysisHealth struct {
	value *CompanyAnalysisExtendedAnalysisHealth
	isSet bool
}

func (v NullableCompanyAnalysisExtendedAnalysisHealth) Get() *CompanyAnalysisExtendedAnalysisHealth {
	return v.value
}

func (v *NullableCompanyAnalysisExtendedAnalysisHealth) Set(val *CompanyAnalysisExtendedAnalysisHealth) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyAnalysisExtendedAnalysisHealth) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyAnalysisExtendedAnalysisHealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyAnalysisExtendedAnalysisHealth(val *CompanyAnalysisExtendedAnalysisHealth) *NullableCompanyAnalysisExtendedAnalysisHealth {
	return &NullableCompanyAnalysisExtendedAnalysisHealth{value: val, isSet: true}
}

func (v NullableCompanyAnalysisExtendedAnalysisHealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyAnalysisExtendedAnalysisHealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
