/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OwnershipOwner struct for OwnershipOwner
type OwnershipOwner struct {
	Name string `json:"name,omitempty"`
	Type string `json:"type,omitempty"`
	CompanyType int32 `json:"company_type,omitempty"`
	ObjectId int32 `json:"object_id,omitempty"`
}
