/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// IndustryCountry struct for IndustryCountry
type IndustryCountry struct {
	Data IndustryCountryData `json:"data,omitempty"`
	Links IndustryCountryLinks `json:"links,omitempty"`
	Countries IndustryCountryCountries `json:"countries,omitempty"`
}
