/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Developments struct for Developments
type Developments struct {
	Data []Development `json:"data,omitempty"`
}
