/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CompanyAnalysisPast struct for CompanyAnalysisPast
type CompanyAnalysisPast struct {
	Growth1y *float32 `json:"growth_1y,omitempty"`
	Growth5y *float32 `json:"growth_5y,omitempty"`
}

// NewCompanyAnalysisPast instantiates a new CompanyAnalysisPast object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyAnalysisPast() *CompanyAnalysisPast {
	this := CompanyAnalysisPast{}
	return &this
}

// NewCompanyAnalysisPastWithDefaults instantiates a new CompanyAnalysisPast object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyAnalysisPastWithDefaults() *CompanyAnalysisPast {
	this := CompanyAnalysisPast{}
	return &this
}

// GetGrowth1y returns the Growth1y field value if set, zero value otherwise.
func (o *CompanyAnalysisPast) GetGrowth1y() float32 {
	if o == nil || o.Growth1y == nil {
		var ret float32
		return ret
	}
	return *o.Growth1y
}

// GetGrowth1yOk returns a tuple with the Growth1y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisPast) GetGrowth1yOk() (*float32, bool) {
	if o == nil || o.Growth1y == nil {
		return nil, false
	}
	return o.Growth1y, true
}

// HasGrowth1y returns a boolean if a field has been set.
func (o *CompanyAnalysisPast) HasGrowth1y() bool {
	if o != nil && o.Growth1y != nil {
		return true
	}

	return false
}

// SetGrowth1y gets a reference to the given float32 and assigns it to the Growth1y field.
func (o *CompanyAnalysisPast) SetGrowth1y(v float32) {
	o.Growth1y = &v
}

// GetGrowth5y returns the Growth5y field value if set, zero value otherwise.
func (o *CompanyAnalysisPast) GetGrowth5y() float32 {
	if o == nil || o.Growth5y == nil {
		var ret float32
		return ret
	}
	return *o.Growth5y
}

// GetGrowth5yOk returns a tuple with the Growth5y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisPast) GetGrowth5yOk() (*float32, bool) {
	if o == nil || o.Growth5y == nil {
		return nil, false
	}
	return o.Growth5y, true
}

// HasGrowth5y returns a boolean if a field has been set.
func (o *CompanyAnalysisPast) HasGrowth5y() bool {
	if o != nil && o.Growth5y != nil {
		return true
	}

	return false
}

// SetGrowth5y gets a reference to the given float32 and assigns it to the Growth5y field.
func (o *CompanyAnalysisPast) SetGrowth5y(v float32) {
	o.Growth5y = &v
}

func (o CompanyAnalysisPast) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Growth1y != nil {
		toSerialize["growth_1y"] = o.Growth1y
	}
	if o.Growth5y != nil {
		toSerialize["growth_5y"] = o.Growth5y
	}
	return json.Marshal(toSerialize)
}

type NullableCompanyAnalysisPast struct {
	value *CompanyAnalysisPast
	isSet bool
}

func (v NullableCompanyAnalysisPast) Get() *CompanyAnalysisPast {
	return v.value
}

func (v *NullableCompanyAnalysisPast) Set(val *CompanyAnalysisPast) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyAnalysisPast) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyAnalysisPast) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyAnalysisPast(val *CompanyAnalysisPast) *NullableCompanyAnalysisPast {
	return &NullableCompanyAnalysisPast{value: val, isSet: true}
}

func (v NullableCompanyAnalysisPast) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyAnalysisPast) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
