/*
 * simply-wallst
 *
 * simply-wallst API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CompanyAnalysisExtendedRawDataInsiderTransactions struct for CompanyAnalysisExtendedRawDataInsiderTransactions
type CompanyAnalysisExtendedRawDataInsiderTransactions struct {
	Data *[]CompanyAnalysisExtendedRawDataInsiderTransactions `json:"data,omitempty"`
}

// NewCompanyAnalysisExtendedRawDataInsiderTransactions instantiates a new CompanyAnalysisExtendedRawDataInsiderTransactions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyAnalysisExtendedRawDataInsiderTransactions() *CompanyAnalysisExtendedRawDataInsiderTransactions {
	this := CompanyAnalysisExtendedRawDataInsiderTransactions{}
	return &this
}

// NewCompanyAnalysisExtendedRawDataInsiderTransactionsWithDefaults instantiates a new CompanyAnalysisExtendedRawDataInsiderTransactions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyAnalysisExtendedRawDataInsiderTransactionsWithDefaults() *CompanyAnalysisExtendedRawDataInsiderTransactions {
	this := CompanyAnalysisExtendedRawDataInsiderTransactions{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CompanyAnalysisExtendedRawDataInsiderTransactions) GetData() []CompanyAnalysisExtendedRawDataInsiderTransactions {
	if o == nil || o.Data == nil {
		var ret []CompanyAnalysisExtendedRawDataInsiderTransactions
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyAnalysisExtendedRawDataInsiderTransactions) GetDataOk() (*[]CompanyAnalysisExtendedRawDataInsiderTransactions, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CompanyAnalysisExtendedRawDataInsiderTransactions) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []CompanyAnalysisExtendedRawDataInsiderTransactions and assigns it to the Data field.
func (o *CompanyAnalysisExtendedRawDataInsiderTransactions) SetData(v []CompanyAnalysisExtendedRawDataInsiderTransactions) {
	o.Data = &v
}

func (o CompanyAnalysisExtendedRawDataInsiderTransactions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableCompanyAnalysisExtendedRawDataInsiderTransactions struct {
	value *CompanyAnalysisExtendedRawDataInsiderTransactions
	isSet bool
}

func (v NullableCompanyAnalysisExtendedRawDataInsiderTransactions) Get() *CompanyAnalysisExtendedRawDataInsiderTransactions {
	return v.value
}

func (v *NullableCompanyAnalysisExtendedRawDataInsiderTransactions) Set(val *CompanyAnalysisExtendedRawDataInsiderTransactions) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyAnalysisExtendedRawDataInsiderTransactions) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyAnalysisExtendedRawDataInsiderTransactions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyAnalysisExtendedRawDataInsiderTransactions(val *CompanyAnalysisExtendedRawDataInsiderTransactions) *NullableCompanyAnalysisExtendedRawDataInsiderTransactions {
	return &NullableCompanyAnalysisExtendedRawDataInsiderTransactions{value: val, isSet: true}
}

func (v NullableCompanyAnalysisExtendedRawDataInsiderTransactions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyAnalysisExtendedRawDataInsiderTransactions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
